# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZA8vDmFTJlboZga2A6Yctb8eiOkw6AAZ
"""

#!pip install tensorflow

#!pip install gdown

#pip install --upgrade tensorflow

#!pip install --upgrade keras
#!pip install streamlit

import streamlit as st
import tensorflow as tf
from PIL import Image
import numpy as np
import gdown
import os

# Direct download link of the model file from Google Drive
url = 'https://drive.google.com/uc?id=1hQ_gEuno0tOtAIx3ReKhS1SnQ4OEdXqx'

# Path to save the downloaded model file
model_path = 'my_model.keras'

# Download the model if it does not exist
if not os.path.exists(model_path):
    with st.spinner('Downloading model...'):
        gdown.download(url, model_path, quiet=False)

# Load the species classification model
model = tf.keras.models.load_model(model_path)

# Load a pre-trained model for general image classification (e.g., MobileNetV2)
general_model = tf.keras.applications.MobileNetV2(weights='imagenet')

# Define the species names
species_names = [
    "Mantled Howler",
    "Patas Monkey",
    "Bald Monkey",
    "Japanese Macaque",
    "Pygmy Marmoset",
    "White Headed Capuchin",
    "Silver Marmoset",
    "Common Squirrel Monkey",
    "Black Headed Night Monkey",
    "Nilgiri Langur"
]

# Define a confidence threshold
CONFIDENCE_THRESHOLD = 0.5  # Adjust this value as needed

# Define a function to preprocess the image for the species model
def preprocess_image(image):
    image = image.resize((64, 64))  # Adjust size to match model input (64x64)
    image = image.convert("RGB")  # Ensure image is in RGB mode
    image = np.array(image)
    image = np.expand_dims(image, axis=0)  # Add batch dimension
    image = image / 255.0  # Normalize
    return image

# Define a function to preprocess the image for the general model
def preprocess_image_general(image):
    image = image.resize((224, 224))  # Adjust size to match MobileNetV2 input (224x224)
    image = image.convert("RGB")  # Ensure image is in RGB mode
    image = np.array(image)
    image = np.expand_dims(image, axis=0)  # Add batch dimension
    image = tf.keras.applications.mobilenet_v2.preprocess_input(image)  # Preprocess for MobileNetV2
    return image

# Define a function to check if the image is a monkey
def is_monkey(image):
    processed_image = preprocess_image_general(image)
    predictions = general_model.predict(processed_image)
    decoded_predictions = tf.keras.applications.mobilenet_v2.decode_predictions(predictions, top=5)
    # Check if any of the top 5 predictions is related to a monkey
    for pred in decoded_predictions[0]:
        if 'monkey' in pred[1] or 'ape' in pred[1]:
            return True
    return False

# Define a function to make species predictions
def predict_species(image):
    processed_image = preprocess_image(image)
    prediction = model.predict(processed_image)
    return prediction

# Custom CSS for background and other elements
st.markdown("""
    <style>
    .main {
        background-color: blue;
    }
    .title {
        color: red;
        font-family: 'Arial';
        text-align: center;
    }
    .uploader {
        text-align: center;
    }
    .prediction {
        font-size: 20px;
        color: indigo;
        font-weight: bold;
        text-align: center;
    }
    .uploaded-image {
        display: block;
        margin-left: auto;
        margin-right: auto;
        border: 5px solid #ccc;
    }
    </style>
    """, unsafe_allow_html=True)

# Streamlit interface with custom styles
st.markdown('<h1 class="title">Monkeys Species Classification Application</h1>', unsafe_allow_html=True)

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption='Uploaded Image.', use_column_width=True, output_format='JPEG', channels='RGB')
    st.write("")
    st.markdown('<div class="prediction">Classifying...</div>', unsafe_allow_html=True)

    # Check if the image is a monkey
    if is_monkey(image):
        # Make species prediction
        prediction = predict_species(image)

        # Get the index of the highest probability
        predicted_index = np.argmax(prediction, axis=1)[0]
        confidence_score = np.max(prediction, axis=1)[0]

        # Check if the confidence score is above the threshold
        if confidence_score >= CONFIDENCE_THRESHOLD:
            # Get the corresponding species name
            predicted_species = species_names[predicted_index]
            # Display the prediction
            st.markdown(f'<div class="prediction">Prediction: {predicted_species} (Confidence: {confidence_score:.2f})</div>', unsafe_allow_html=True)
        else:
            # Display a message if confidence is below the threshold
            st.markdown('<div class="prediction">The uploaded image does not match any known monkey species.</div>', unsafe_allow_html=True)
    else:
        # Display a message if the image is not a monkey
        st.markdown('<div class="prediction">The uploaded image is not recognized as a monkey.</div>', unsafe_allow_html=True)